#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<string.h>

void optionThree(){
    startopt3:
    system("cls");
    HANDLE hConsole;
    hConsole=GetStdHandle(STD_OUTPUT_HANDLE);
    printf("\t\t\t\t\t\t      ********************\n");
    printf("\t\t\t\t\t\t      ** MEMBER PROJECT **\n");
    printf("\t\t\t\t\t\t      ********************\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,96);
    for(int i=0;i<34;i++) printf("%c",16);
    SetConsoleTextAttribute(hConsole,244);
    printf("\n\n\t\t\t\t\t\t   1.Chann Kimlong\n\t\t\t\t\t\t   2.So Kimlang\n\t\t\t\t\t\t   3.Sin Sonita\n\t\t\t\t\t\t   4.Sakura\n\t\t\t\t\t\t   0.Exit\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,96);
    for(int i=0;i<34;i++) printf("%c",17);


    SetConsoleTextAttribute(hConsole,246);
    printf("\n\n\t\t\t\t\t\t>>>");
    SetConsoleTextAttribute(hConsole,241);
    printf("Choose option to see our info");
    SetConsoleTextAttribute(hConsole,246);
    printf("<<<\n");
    SetConsoleTextAttribute(hConsole,241);
    //scanf(" %d", &option3);
    int option3=getch();
    int exitOpt3;
    switch(option3){
case 48:
    break;
a3:
case 49:{
system("cls");
system("cls");
    printf("\t\t\t\t\t\t       ===================\n");
    printf("\t\t\t\t\t\t       == MY INFOMATION ==\n");
    printf("\t\t\t\t\t\t       ===================\n\n");
    printf("\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",16);
    printf("\n\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tName         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Chann Kimlong\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tDate of birth day : ");
SetConsoleTextAttribute(hConsole,242);
printf("11 March 2003\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tAge          : ");
SetConsoleTextAttribute(hConsole,242);
printf("19 years old\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tMajor        : ");
SetConsoleTextAttribute(hConsole,242);
printf("Computer science\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tUniversity   : ");
SetConsoleTextAttribute(hConsole,242);
printf("CADT\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tCarreer goal : ");
SetConsoleTextAttribute(hConsole,242);
printf("Mobile App developer\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFrom         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Preyveng Province\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFacebook     : ");
SetConsoleTextAttribute(hConsole,242);
printf("Kim Long\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tInstagram    : ");
SetConsoleTextAttribute(hConsole,242);
printf("Kimlong_chann101\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tTelegram     : ");
SetConsoleTextAttribute(hConsole,242);
printf("+855 85739468\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",17);
    SetConsoleTextAttribute(hConsole,241);
printf("\n\n");
printf("\t\t\t\t\t\tDo you want to exit?(yes=0/no=1)>>");
scanf(" %d", &exitOpt3);
if(exitOpt3==0) goto startopt3;
if(exitOpt3==1) goto b3;
break;
}
b3:
case 50:{
system("cls");
    printf("\t\t\t\t\t\t       ===================\n");
    printf("\t\t\t\t\t\t       == MY INFOMATION ==\n");
    printf("\t\t\t\t\t\t       ===================\n\n");
    printf("\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",16);
    printf("\n\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tName         : ");
SetConsoleTextAttribute(hConsole,242);
printf("So kimlang\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tDate of birth day : ");
SetConsoleTextAttribute(hConsole,242);
printf("17 March 2004\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tAge          : ");
SetConsoleTextAttribute(hConsole,242);
printf("18 years old\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tMajor        : ");
SetConsoleTextAttribute(hConsole,242);
printf("Computer science\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tUniversity   : ");
SetConsoleTextAttribute(hConsole,242);
printf("CADT\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tCarreer goal : ");
SetConsoleTextAttribute(hConsole,242);
printf("Mobile App developer\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFrom         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Battombong Province\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFacebook     : ");
SetConsoleTextAttribute(hConsole,242);
printf("Kimlang So\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tInstagram    : ");
SetConsoleTextAttribute(hConsole,242);
printf("so_kimlang17\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tTelegram     : ");
SetConsoleTextAttribute(hConsole,242);
printf("+855 10283312\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",17);
    SetConsoleTextAttribute(hConsole,241);
printf("\n\n");
printf("\t\t\t\t\t\tDo you want to exit?(yes=0/no=1)>>");
scanf(" %d", &exitOpt3);
if(exitOpt3==0) goto startopt3;
if(exitOpt3==1) goto b3;
break;
}
c3:
case 51:{
system("cls");
    printf("\t\t\t\t\t\t       ===================\n");
    printf("\t\t\t\t\t\t       == MY INFOMATION ==\n");
    printf("\t\t\t\t\t\t       ===================\n\n");
    printf("\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",16);
    printf("\n\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tName         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Sin Sonita\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tDate of birth day : ");
SetConsoleTextAttribute(hConsole,242);
printf("21 December 2001\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tAge          : ");
SetConsoleTextAttribute(hConsole,242);
printf("20 years old\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tMajor        : ");
SetConsoleTextAttribute(hConsole,242);
printf("Computer science\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tUniversity   : ");
SetConsoleTextAttribute(hConsole,242);
printf("CADT\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tCarreer goal : ");
SetConsoleTextAttribute(hConsole,242);
printf("software Engineer\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFrom         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Kondal Province\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFacebook     : ");
SetConsoleTextAttribute(hConsole,242);
printf("sin Sonita\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tInstagram    : ");
SetConsoleTextAttribute(hConsole,242);
printf("sin_sonitaa\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tTelegram     : ");
SetConsoleTextAttribute(hConsole,242);
printf("+855 87 854 410\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",17);
    SetConsoleTextAttribute(hConsole,241);
printf("\n\n");
printf("\t\t\t\t\t\tDo you want to exit?(yes=0/no=1)>>");
scanf(" %d", &exitOpt3);
if(exitOpt3==0) goto startopt3;
if(exitOpt3==1) goto b3;
break;
}
case 52:{
system("cls");
    printf("\t\t\t\t\t\t       ===================\n");
    printf("\t\t\t\t\t\t       == MY INFOMATION ==\n");
    printf("\t\t\t\t\t\t       ===================\n\n");
    printf("\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",16);
    printf("\n\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tName         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Saroun Sakura\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tDate of birth day : ");
SetConsoleTextAttribute(hConsole,242);
printf("21 september 2004\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tAge          : ");
SetConsoleTextAttribute(hConsole,242);
printf("18 years old\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tMajor        : ");
SetConsoleTextAttribute(hConsole,242);
printf("Computer science\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tUniversity   : ");
SetConsoleTextAttribute(hConsole,242);
printf("CADT\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tCarreer goal : ");
SetConsoleTextAttribute(hConsole,242);
printf("Web designer\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFrom         : ");
SetConsoleTextAttribute(hConsole,242);
printf("Banteay Meanchey Province\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tFacebook     : ");
SetConsoleTextAttribute(hConsole,242);
printf("Sa kxra\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tInstagram    : ");
SetConsoleTextAttribute(hConsole,242);
printf("qurrv__\n");
SetConsoleTextAttribute(hConsole,241);
printf("\t\t\t\t\t\tTelegram     : ");
SetConsoleTextAttribute(hConsole,242);
printf("+855 87323031\n");
    printf("\n\t\t\t\t\t\t");
    SetConsoleTextAttribute(hConsole,71);
    for(int i=0;i<34;i++) printf("%c",17);
    SetConsoleTextAttribute(hConsole,241);
printf("\n\n");
printf("\t\t\t\t\t\tDo you want to exit?(yes=0/no=1)>>");
scanf(" %d", &exitOpt3);
if(exitOpt3==0) goto startopt3;
if(exitOpt3==1) goto b3;

break;
}
    }

}
